site:
  name: JyotirSetu
  site: 'https://www.jyotirsetu.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null # Add after Google Search Console verification

# Default SEO metadata
metadata:
  title:
    default: JyotirSetu
    template: '%s — JyotirSetu'
  description: 'Professional astrology, palmistry & numerology consultations by Astrologer Punita Sharma.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: JyotirSetu
    images:
      - url: '~/assets/images/logo.png' # Your logo for social sharing
        width: 1200
        height: 628
        alt: 'JyotirSetu Logo'
    type: website
  twitter:
    handle: null
    site: null
    cardType: summary_large_image
    images:
      - url: '~/assets/images/logo.png' # Logo for Twitter card
        width: 1200
        height: 628
        alt: 'JyotirSetu Logo'

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # Add after Google Analytics setup

ui:
  theme: 'system'
